### ISSUE TITLE
Read movies

### ISSUE THREAD

**Issue by bigornoo** [SpaceK33z/plex-tvtime-webhook#2]
Hi,
when I try to read a movie, I've this : 

 (node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tvdb' of null
tvtimeplex    |     at /opt/plex-tvtime-webhook/index.js:46:35
tvtimeplex    |     at Layer.handle [as handle_request] (/opt/plex-tvtime-webhook/node_modules/express/lib/router/layer.js:95:5)
tvtimeplex    |     at next (/opt/plex-tvtime-webhook/node_modules/express/lib/router/route.js:137:13)
tvtimeplex    |     at Array.<anonymous> (/opt/plex-tvtime-webhook/node_modules/multer/lib/make-middleware.js:53:37)
tvtimeplex    |     at listener (/opt/plex-tvtime-webhook/node_modules/on-finished/index.js:169:15)
tvtimeplex    |     at onFinish (/opt/plex-tvtime-webhook/node_modules/on-finished/index.js:100:5)
tvtimeplex    |     at callback (/opt/plex-tvtime-webhook/node_modules/ee-first/index.js:55:10)
tvtimeplex    |     at IncomingMessage.onevent (/opt/plex-tvtime-webhook/node_modules/ee-first/index.js:93:5)
tvtimeplex    |     at emitNone (events.js:111:20)
tvtimeplex    |     at IncomingMessage.emit (events.js:208:7)
tvtimeplex    | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by reject
ing a promise which was not handled with .catch(). (rejection id: 3)

But everything is ok with a tv show. 

An idea ? Thank you.

**Comment by SpaceK33z** [comment]
I have not yet tested this with TVTime's new movie feature. I don't have time for it now, but if anyone wants to contribute it with a pull requests that's very welcome!

**Comment by bigornoo** [comment]
It will be nice but I don't know JavaScript :(
